### ISSUE TITLE
Prevent the creation of a canvas

### ISSUE THREAD

**Issue by clankill3r** [piqnt/planck.js#102]
How can I prevent the creation of a canvas? I make a SVG, and I don't want the canvas at all.
So hiding it is no option cause then it will still take cpu usage in the background.

**Comment by shakiba** [comment]
What about [this](https://github.com/shakiba/planck.js/blob/master/README.md#rendering-and-integration)?

**Comment by shakiba** [comment]
Here is how it works: https://codepen.io/piqnt/pen/XWrzNBy

**Comment by shakiba** [comment]
Closing inactive issues, please feel free to reopen.
