### ISSUE TITLE
Very simple renderer without third-party libraries

### ISSUE THREAD

**Issue by RealPeha** [piqnt/planck.js#103]
Hello
I wrote a very simple library (for my project) for those who do not want to use testbet with stage-js or any other library
So far, everything is primitive, but working
I think many who use planck-js will be interested.

Github: https://github.com/RealPeha/planck-renderer/tree/master
npm: planck-renderer

**Comment by shakiba** [comment]
This is great, thanks for sharing! :) It would be great if you share an online example. I can add a link in readme file to your project.

**Comment by RealPeha** [comment]
It would be great if you added a link to my project in your readme. I will definitely make an online example soon

Thank you very much ;)

**Comment by shakiba** [comment]
Sure, let me know when it is ready, I will add it. You can serve your library file from jsdelivr and to make an online example with codepen or jsbin:
https://www.jsdelivr.com/package/npm/planck-renderer

**Comment by shakiba** [comment]
@RealPeha What about separating renderer from runner, so that you can have multiple renderer in same branch and make one build file for each renderer, for example:
```
planck-renderer-canvas.js
planck-renderer-stage.js
planck-renderer-svg.js
...
```

**Comment by shakiba** [comment]
Also I added a link to your project in readme file.

**Comment by RealPeha** [comment]
@shakiba Hello! I'm here again :)
I took into account your advice and divided the renderer and runner. I also added an online example - https://codesandbox.io/s/hungry-colden-70rji
Thanks so much for the support!

Also at the moment there is a problem with rendering wide lineWindth, so far I could not solve it

(I also have problems with the English language, so sorry :)

**Comment by shakiba** [comment]
This is awesome, thanks for your work!
