### ISSUE TITLE
what is best practice to process collisions in planck?

### ISSUE THREAD

**Issue by djrolleyes** [piqnt/planck.js#107]
There is an example I found in http://piqnt.com/planck.js/8-Ball with this code:

```
world.on('post-solve', function(contact) {
    var fA = contact.getFixtureA(), bA = fA.getBody();
    var fB = contact.getFixtureB(), bB = fB.getBody();

    var pocket = fA.getUserData() === pocketFixDef.userData && bA || fB.getUserData() === pocketFixDef.userData && bB;
    var ball = fA.getUserData() === ballFixDef.userData && bA || fB.getUserData() === ballFixDef.userData && bB;

    // do not change world immediately
    setTimeout(function() {
      if (ball && pocket) {
        world.destroyBody(ball);
      }
    }, 1);
  }); 
```
So, what is best practice to process collisions in planck? For example I have a multiple bodies with multiple fixtures and I want to listen only 2 bodies was collided. How to achive that?

And another question: why should I use setTimeout to destroy body?

**Comment by shakiba** [comment]
You are correct, that's how you can listen to collisions (listen to collisions and check if it is between bodies you are interested in).

World is not supposed to change when a 'step' is in progress, so 'setTimeout' is a simple hack to postpone changes. You could also put bodies to be removed in an array and remove them after step is finished.

**Comment by djrolleyes** [comment]
@shakiba thanks! But when step is finished? is it sync method? When should I call destroyBody?

**Comment by shakiba** [comment]
Generally speaking anywhere outside world's callback/events would work.
