### ISSUE TITLE
Help with the car example

### ISSUE THREAD

**Issue by TheRatBand** [piqnt/planck.js#110]
Could someone help me write a couple lines of code so that when you press the left shift button it makes a really big speed boos so that I know how to set speeds? Thanks!

**Comment by shakiba** [comment]
It is more ui and game logic question than physics engine.
- You could change [testbed](https://github.com/shakiba/planck.js/blob/master/testbed/index.js#L321) to store `e.shiftKey` state in activeKeys, or do something similar in you own code.
- To implement speed boost you need more than setting speed. One way to implement it is adding a boost variable and in each 'step' consume half (or any portion) of boost by removing it from boost variable and adding it to normal car speed (`setMotorSpeed`), until boost is emptied.
