### ISSUE TITLE
Handle onMouseDown and onMouseUp on Body or Fixture

### ISSUE THREAD

**Issue by cedricdelpoux** [piqnt/planck.js#111]
Hello, 

I would like to know when an element is dragged and I could not find a way to retrieve these data. 
Can I add an event listener with `onMouseDown` and `onMouseUp` somewhere?

Thank you

**Comment by shakiba** [comment]
You could find what fixture/body a point (for example mouse click location) intersect with and use that to implement mouse events which is [how testbed works](https://github.com/shakiba/planck.js/blob/master/testbed/index.js#L241), however planck-js is just physics and does not process ui events.
