### ISSUE TITLE
A more detailed explanation of testbed size, ratio

### ISSUE THREAD

**Issue by burakk** [piqnt/planck.js#118]
Hi, can someone explain the reason of  testbed.width=80, testbed.height=60 while the canvas' size of the examples on the web is 900px X 600px. And why the value of ratio is 16? What is the relation between those numbers?

**Comment by shakiba** [comment]
Testbed size is in physics unit, canvas is in display pixels, testbed scales given width/height to fit in canvas.

Ratio will be calculated dynamically in future, it is used for rendering.

**Comment by shakiba** [comment]
There is a new [testbed doc](https://piqnt.com/planck.js/docs/testbed) which covers width/height.
