### ISSUE TITLE
[Question] Very Inconsistent function between computers.

### ISSUE THREAD

**Issue by ChristianTucker** [piqnt/planck.js#159]
I've been working quite heavily on the "Physics" for our game and we're quite happy with the movement system that we've created so far thanks to all of the information available online. 

**We have tested this on 7 computers and only 1 has had the issue.**

Here's a few parameters that I can guarantee:

1. All Computers are using intel processors
2. All Computers are using NVidia GPUs
3. All Browsers are up to date 
4. Problem is PC specific, not browser specific from what I can tell. (Chrome, Edge, Opera, Firefox, issue exists on all or none)
5. All tests are run from the piqnt space using the `planck.testbed`
6. All PCs are running windows 10.

Here's the code that's causing the problem (note: we stripped everything away until this was the last thing) in `testbed.step`:  Code also found in [iForce2D (Moving at a constant Speed)](https://www.iforce2d.net/b2dtut/constant-speed) We're using forces for everything where possible not manually setting the velocity at all. All objects have a friction of 0. 

```js
let drag = jumpChangedDirections ? movementDrag : 0;
let desiredVelocity = (movementSpeed - drag) * movementDirection;
let change = desiredVelocity - currentVelocity.x; 
let force = mass * change / (1 / 60);   // 60hz
let walkingForce = Vec2(force, 0); 
player.applyForceToCenter(walkingForce); 
```
The `mass` and `currentVelocity` are just `body#getter` shorthand variables for readability. 

On most machines, everything runs perfectly and we good a smooth movement experience that looks something like this: 
![Example](https://i.imgur.com/EUeNpji.gif)

However, on the PCs that have this problem, whenever the user attempts to move (which calls the code above in `testbed.step` they start to completely freak out. 
![Example](https://i.imgur.com/vmBKeU9.gif)

We did some debugging remotely and I found that the cause of this issue seems to be over-compensation. Usually the value of `change` is only adjusted when you are starting and stopping. However, in this example, `change` gets set showing that the current x velocity is `1.8...` so it compensates for that with some force. (Our gravity is really heavy, by the way)

But then it seems to permenantly compensate back and forth and never find the sweet spot again of moving at `movementSpeed` or standing still.

![Example](https://i.imgur.com/SZyI787.png)

I'm really not sure what would cause this to happen, as most computers seem to have no problems running this simulation. I've done everything I can think of, but it's a huge concern for my game. 

**Note**: A force is usually only applied once during our movement, unless the direction is changed or the player stops moving. This force value is calculated to be 420 or -420 depending on direction, and 840/-840 when switching directions. For some reason, on this one computer, it's being adjusted constantly. There's no friction, just to double-clarify.  

**Note 2**: Also a strange thing to notice, but the problem starts at a velocity of 1.8, but... in our application velocity is almost always `7, 0 or -7` (movementSpeed) or `3, 0, or -3` (movementSpeed - jumpDrag)

**Comment by shakiba** [comment]
I will check this out this week, meanwhile to verify it is planck.js library issue could you please test it without testbed/space as well. See this [hello world file](https://github.com/shakiba/planck.js/blob/master/HelloWorld.js) for an example (you can run it in browser).

**Comment by ChristianTucker** [comment]
Just going to leave this here for now... our problematic machine is currently not available for testing (but will be later tonight (CST)). I've created a GitHub repository with all of the code and some debug text. 

Heres the [link to the source code](https://github.com/ChristianTucker/planck-js-issue-159)
Heres the [github pages link](https://christiantucker.github.io/planck-js-issue-159/)

Below you can see a recording of what the debug text looks like when it's running correctly, I will comment again with the results with the other machine later tonight.

![Running Correct](https://i.imgur.com/uyxjYQ6.gif)

**Note:** I just wanted to note that the values are the same on all of our good machines, even down to the last decimal place for the position, surprising as I expected some floating point precision problems to cause that to vary minorly.

**Comment by ChristianTucker** [comment]
Just wanted to confirm that the outputs are as expected on the problematic computer as well, the source code i provided has the same objects and code that will cause the issue inside of the Space testbed. I'm currently writing out my own renderer so I'll let you know if the issue appears outside of the space.

**Comment by ChristianTucker** [comment]
Okay, so thank you for that recommendation of running things outside of the testbed to see if we could isolate the issue to either `space/testbed`. We've run the tests on our problematic machine and the `[github reproduction](https://github.com/ChristianTucker/planck-js-issue-159)` ([Github Page Link](https://christiantucker.github.io/planck-js-issue-159/)) runs perfectly fine while the [Space Sandbox](https://piqnt.com/space/ga50lu9qA) maintains the error.

I noticed something else, when running the application outside of the testbed, the position stabilizes at `Y: 0.5149...916877` however on the testbed it's `5.149.....98` this could just be an instance of floating point precision errors, but I find it strange that this is the case on all of our machines. (and a steady difference).

**Comment by shakiba** [comment]
Could you please try this:
```js
testbed.step = (dt) => {
    timeStep = dt / 1000;
    // ...
}
```

**Comment by ChristianTucker** [comment]
This effected the smoothness of the machines that it was working on (felt a bit more like it was stuttering) and did not solve the problem on the broken machine.

**Comment by shakiba** [comment]
Hmm, interesting! I don't know really, do you see same issue if instead of keyboard events you program movements?

**Comment by ChristianTucker** [comment]
@shakiba I'm going to be away for a few days, but I will send it off to be tested when I'm back.

**Comment by shakiba** [comment]
Great, thanks! Space runtime was built by extending the testbed (which is in this repo), if it helps you debug the issue. When I have some free time I will clean up and release or merge space runtime with testbed.

**Comment by ChristianTucker** [comment]
@shakiba Hey there, we figured out what's causing the issue! The computer that was having the issue was one of our content creators which has a high-end build. His display refresh rate is set to run at **300.180hz**... yeah, you read that right. I was baffled. Anyway, I made him set his display refresh rate to 60hz and there were no problems what-so-ever.  Hopefully that helps you getting the issue resolved!  The `x.180hz` part really threw me off, maybe that's the cause?

**Comment by shakiba** [comment]
Yeah, that makes, that's why I was suspect `step` is the issue--currently step is called on each frame (rather than each physics step), while physic is called each 1/60 seconds, so with 180hz frame rate `step` is called 3 times more than it should. I will fix this issue.

I changed script limit to 1M (it was 10K before).

**Comment by shakiba** [comment]
Instead of changing `testbed.step`, I added `pre-step` and `post-step` events to World and will deprecate `testbed.step` in future. This will make it easier to run same code consistently with and without testbed. 

```ts
world.on('pre-step', function(deltaTime) => {
});
world.on('post-step', function(deltaTime) => {
});
```
@ChristianTucker Could you please see if this solved your issue?

cc @zOadT
