### ISSUE TITLE
Typescript - could-not-find-a-declaration-file-for-module-planck-js. Version 0.3.27

### ISSUE THREAD

**Issue by MercurialUroboros** [piqnt/planck.js#165]
Hello. I'm having trouble using version 0.3.27 with typescript.

Could not find a declaration file for module 'planck-js'. '/Users/user/Desktop/experiments/planktest/node_modules/planck-js/lib/index.js' implicitly has an 'any' type.

Reverting to 0.3.26 fixes the issue.

**Comment by shakiba** [comment]
Thanks for reporting, it should be fixed now.
