### ISSUE TITLE
How to declare a MassData to use with getMassData

### ISSUE THREAD

**Issue by bobcgausa** [piqnt/planck.js#185]
i tried var md = new planck.MassData() and error message is no constructor
i'm trying to put a dot on the center of mass

btw a getCenterOfMass ()  would be useful

**Comment by shakiba** [comment]
It's just an object, you could just create an object like `md = { mass: 0, center: Vec2(), I: 0 }`

**Comment by shakiba** [comment]
> btw a getCenterOfMass () would be useful

`getWorldCenter()` and `getLocalCenter()` return the center of mass.
