### ISSUE TITLE
documentation for Transform is wrong, or at least incomplete

### ISSUE THREAD

**Issue by bobcgausa** [piqnt/planck.js#189]
describes position/rotation:number but getTransform returns internal rep instead of converting back to angle
i think the expected return is {position: angle}
there is documentation on q but it is cryptic
q: Rot

Defined in dist/planck.d.ts:369

Defined in src/common/Transform.ts:44

rotation rotation

o {p: o, q: o, constructor: Object}
p: o
x: 1.3333333333333333
y: 2
<constructor>: "o"
q: o
s: 0.3894183423086505
c: 0.9210609940028851
<constructor>: "o"
<constructor>: "o"

**Comment by shakiba** [comment]
Rot (rotation) is internally stored as `{ s: sin(angle), c: cos(angle)}`, and Transform as `{p: Vec2, q: Rot}`.

I just update the code and added js-doc for rotation (api-doc and typescript definitions will update by the next build).

Thanks for reporting this!
