### ISSUE TITLE
Haxe externs

### ISSUE THREAD

**Issue by NicolasVereenoghe** [piqnt/planck.js#19]
Not an issue, but just to let you know that I am working on externs for Haxe (not shure of the best practice to post this) :

https://github.com/NicolasVereenoghe/git.vega.pixi4/tree/master/haxe/lib/planck%2Cjs

It's a first try, and for now the externs are hosted into my framework repository.

I'm going to deal with serious testing the coming days. I hope it will make the job ^^

If you're interested, try it or tell ... I may create another repository for the Haxe externs, for now I'm not sure :)

**Comment by shakiba** [comment]
Cool! Does it require specifying static types for methods' arguments and return?

**Comment by NicolasVereenoghe** [comment]
They are already defined into the externs :
sometimes I had to create some new "typedef" that conform to yours :
https://github.com/NicolasVereenoghe/git.vega.pixi4/blob/master/haxe/lib/planck%2Cjs/0%2C1%2C34/src/planck/World.hx#L10-L29

... or sometimes they are just externs of yours :
https://github.com/NicolasVereenoghe/git.vega.pixi4/blob/master/haxe/lib/planck%2Cjs/0%2C1%2C34/src/planck/collision/Distance.hx#L14-L43

For now I've just checked the instances are created (World, Body .... Transform ...) and filled correctly. I followed the provided index.js file and tryed to deal with code that is exposed (not all protected members, not the Solver class, I believe the latter can remain hidden for now)

More testing is needed, I work for a client and I will test it this week ....

**Comment by shakiba** [comment]
That's interesting and very helpful!  Do you know how does it compare to TypeScript types? Because someone asked me about it before.

**Comment by NicolasVereenoghe** [comment]
Sorry, I dont have expertise with TypeScript

**Comment by shakiba** [comment]
Ah, ok.  Please keep me updated about your work, I'm interested to see how it works.

**Comment by NicolasVereenoghe** [comment]
Hello,

My work is still in progress, and for now the planckjs seems to run properly with the Haxe externs.
I cannot show a demo because it's for a client. It's a mini game where you need to complete a level by adding blocks, so that a ball can travel to a goal.

From my first post, I had to adjust the externs to conform to your code, I updated them into my framework repository (see previous links). I copy my "commit comments" here :
. optional Body::createFixture parameters
. optional parameters for Fixture constructor
. added FixtureDef::shape field
. adjusted signature for World::on and World::off events registration functions
. added constants for world events labels (WORLD_REMOVE_BODY,WORLD_REMOVE_JOINT,WORLD_REMOVE_FIXTURE,WORLD_CONTACT_BEGIN,WORLD_CONTACT_END,WORLD_CONTACT_PRE,WORLD_CONTACT_POST)
. warning : you have to explicitly set a body as dynamic, even if its fixtures have a non 0 density

I continue the testings :)

**Comment by NicolasVereenoghe** [comment]
Hello, here a game demo extracted from my work for my client. I think I can share this :
https://github.com/NicolasVereenoghe/vega.labo.pampamplanck

The game is redeveloped from former Flash Box2D sources. Mechanics are very simple. It conforms to the original game. No issues for now, just some adjustments to adapt to the last Box2D API.

**Comment by shakiba** [comment]
Awesome! :)  I'm glad it worked for you.  I will add it to a new demo list in near future.
