### ISSUE TITLE
body.shouldCollide documentation is inaccurate in use of the word "prevent"

### ISSUE THREAD

**Issue by bobcgausa** [piqnt/planck.js#190]
/**
   * This is used to test if bodies connected by the same joint will register a collision.
   * Returns false only if body is in joint list and its collideConnected flag is false
   */ 
----------------------------
/**
   * This is used to prevent connected bodies (by joints) from colliding,
   * depending on the joint's collideConnected flag.
   */
  shouldCollide(that: Body): boolean {
    // At least one body should be dynamic.
    if (this.m_type != DYNAMIC && that.m_type != DYNAMIC) {
      return false;
    }
    // Does a joint prevent collision?
    for (let jn = this.m_jointList; jn; jn = jn.next) {
      if (jn.other == that) {
        if (jn.joint.m_collideConnected == false) {
          return false;
        }
      }
    }
    return true;
  }

**Comment by Toby222** [comment]
```js
/**
 * This is used to test if bodies connected by the same joint will register a collision.
 * Returns false only if body is in joint list and its collideConnected flag is false
  */

/**
 * This is used to prevent connected bodies (by joints) from colliding,
 * depending on the joint's collideConnected flag.
 */
shouldCollide(that: Body): boolean {
  // At least one body should be dynamic.
  if (this.m_type != DYNAMIC && that.m_type != DYNAMIC) {
    return false;
  }
  
  // Does a joint prevent collision?
  for (let jn = this.m_jointList; jn; jn = jn.next) {
    if (jn.other == that) {
      if (jn.joint.m_collideConnected == false) {
        return false;
      }
    }
  }
  return true;
}
```

**Comment by shakiba** [comment]
Thanks, fixed it in the source code (will generate updated api docs soon).
