### ISSUE TITLE
Processing & Memory 

### ISSUE THREAD

**Issue by Cdvalencia** [piqnt/planck.js#196]
Hi Shakiba. 

i am using "planck-with-testbed.js". and each time that i need restart elements and clear my world, i execute destroyBody by all elements list

```
nextBody=world.getBodyList();
while (nextBody) {
  world.destroyBody(nextBody);
  nextBody=nextBody.getNext();
}
```

but the elements continuos  consuming memory. 

![image](https://user-images.githubusercontent.com/4379656/118062266-3a375500-b35c-11eb-8aee-6937e97526e1.png)

each time that restore elements, the memory to be duplicate and make my app each time more slow.

exists some way one function, that allow clear all elements in my world automatically.

**Comment by shakiba** [comment]
Thanks for reporting, I will check it out.
Does it happen only with testbed, or do you see same issue with core library as well?

**Comment by Cdvalencia** [comment]
i only have used the testbet.

**Comment by bobcgausa** [comment]
Be aware that destroyBody is ignored if invoked during a callback

**Comment by shakiba** [comment]
@quinton-ashley It seems you discussed it (here)[https://github.com/piqnt/planck.js/issues/226] and you were able to resolve the issue in your case? Were you able to confirm that there was not memory leak when removing bodies, or should I try to reproduce this?

**Comment by quinton-ashley** [comment]
Yup all good it was resolved

**Comment by shakiba** [comment]
@Cdvalencia It seems it works fine for Quinton, so I'm closing this. But please feel free to open if needed, and it would be helpful if you could provide an example (without any other library) to reproduce it.
