### ISSUE TITLE
Changing a circle collider's friction doesn't make it roll slower

### ISSUE THREAD

**Issue by quinton-ashley** [piqnt/planck.js#229]
I recently had a student show me that changing a circle collider's `friction` doesn't make it roll slower, neither does changing the `friction` of the box or chain collider it rolls on.

The student and I expected `friction` to affect the rate at which a ball rolls. I know that users could use `rotationDrag` but when users just try to change the friction of a rotated floor it's confusing that it doesn't work.

Could this bug be fixed in planck?

**Comment by shakiba** [comment]
I made an example here: https://piqnt.com/space/34SG2bT9V

Slipping is faster, and the reason is explained [here](https://physics.stackexchange.com/questions/675684/): 

> Less energy is converted into rotational kinetic energy if there is slipping, and thus (per energy conservation) more is converted into translational kinetic energy, which is a measure of the falling speed.
