### ISSUE TITLE
ERROR changing a collider's mass cancels its linearVelocity

### ISSUE THREAD

**Issue by quinton-ashley** [piqnt/planck.js#263]
Changing a collider's mass using `body.setMassData` cancels its linearVelocity. I think linearVelocity should be maintained in most cases. Perhaps there's a bug in how the collider's new linearVelocity is calculated.

**Comment by shakiba** [comment]
I guess it was fixed [here](https://github.com/piqnt/planck.js/commit/cb7052f1c17210ff0f4211055d13723fe33e64c7)

Are you using the latest version?

**Comment by quinton-ashley** [comment]
yeah I'm using v1 beta 15 planck.min.js

**Comment by shakiba** [comment]
Ops, that commit fixes resetMassData; setMassData was not fixed. I just fixed it and published the update.

**Comment by quinton-ashley** [comment]
Awesome! thank you 🙏🏻

**Comment by shakiba** [comment]
Thanks for reporting the issue!
