### ISSUE TITLE
pointers on how to network planck

### ISSUE THREAD

**Issue by mreinstein** [piqnt/planck.js#272]
I'd like to run planck across a few clients, using an authoritative server model.  I understand how to do this in terms of the basics (fixing the time step, keeping the simulation deterministic, etc.)

I'm not sure how I would serialize/deserlialize planck's internals for each fixed step.  Is there an API I can use for this? Or something higher level, where someone has attempted this already.

**Comment by mreinstein** [comment]
Here's a list of things so far that seem like might be sufficient to sync a physics object's state:
* object id (does planck.js generate one for all objects/fixtures/etc. ?)
* angle
* angularVelocity
* position vec
* linear velocity (vec)

Are there any other things that might need to be sync'd?  I'm not sure how I'd go about syncing a joint constraint for example

**Comment by zOadT** [comment]
Hey! There is a serializer in `src/serializer` already. It isn't optimized for file size, but you can probably follow it for your implementation

**Comment by mreinstein** [comment]
Ah, thanks for the pointer!  So it seems this serializer is just enumerating all the object/array props, rather than a hardcoded list.

**Comment by zOadT** [comment]
I don't think it just enumerates all props, see for example `_serialize` in Body.ts. Every class defines what properties are relevant this way (so it is hardcoded per class)

**Comment by mreinstein** [comment]
Oops! I completely misinterpreted what was going on in src/serializer.ts. Thanks again, this is super helpful!

**Comment by shakiba** [comment]
Current serializer is optimized for saving/loading a world in a readable format, and is not optimized for fast and efficient networking.

For networking I recommend directly iterating over all objects and fields and write to and read from an efficient stream.

**Comment by shakiba** [comment]
Hmm, I'm not quite sure, but happy to help with implementation.

We probably need to implement an interface like current serialize but write to a streaming interface (instead of json).

We also need to find out the answer to your question, probably we can see how this is implemented in C++ for Box2D.

**Comment by mreinstein** [comment]
I don't think planck needs to specifically do anything in this case.  The networking strategy and the game/simulation structure seem to drive how/what is needed to sync. That's very hard to encapsulate without being too prescriptive.  (I'm not interested in having a framework approach that tries to take over game responsibilities for me, or any other heavy abstractions)

I think it's sufficient to point people at the existing serializers. If you wanted to do something maybe there could be a little blurb in the `README.md` pointing out where the existing serializing code lives.
