### ISSUE TITLE
Docs reference non-existent WheelJoint.js example

### ISSUE THREAD

**Issue by rgov** [piqnt/planck.js#287]
https://github.com/piqnt/planck.js/blob/4b6d6ec0ab341d0cea7b3ec4b5236fca3fdd7200/docs/pages/joint/wheel-joint.md?plain=1#L2-L5

There is no WheelJoint.js.

There is [WheelJoint.ts](https://github.com/piqnt/planck.js/blob/master/src/dynamics/joint/WheelJoint.ts) which is the implementation of the joint. Is that what it means? Car.js is an example, it so it sounds like WheelJoint.js is an example (like there is MotorJoint.js).

**Comment by shakiba** [comment]
WheelJoint refers to the joint class (I updated the doc).
