### ISSUE TITLE
Turn off mouse interaction in testbed

### ISSUE THREAD

**Issue by rgov** [piqnt/planck.js#289]
I'm not sure if it's possible to disable the mouse in the testbed. For example setting `testbed.mouseForce = 0` triggers some other behavior rather than disabling it:

https://github.com/piqnt/planck.js/blob/4b6d6ec0ab341d0cea7b3ec4b5236fca3fdd7200/testbed/StageTestbed.ts#L243-L249

The closest I can get is `testbed.mouseForce = 0.001` which is not truly disabled and difficult to discover.

**Comment by shakiba** [comment]
I will try to implement this in next testbed release.

**Comment by shakiba** [comment]
I fix for this, in v1.3.0

With the fix, you need to set mouseForce to 0 to disable it.
