### ISSUE TITLE
Uncaught TypeError: class constructors must be invoked with 'new'

### ISSUE THREAD

**Issue by oodzchen** [piqnt/planck.js#291]
I've follow the official doc to create a simple demo, but got this error
> Uncaught TypeError: class constructors must be invoked with 'new'
    WorldStageNode2 StageTestbed.ts:469
    start StageTestbed.ts:193
    <anonymous> main.js:7

Here's my code
```javascript
import './style.css'
import { World, Testbed, Vec2, Edge } from 'planck/with-testbed'

const testbed = Testbed.mount()
const world = new World(new Vec2(0, -10))

testbed.start(world)

let platform = world.createBody({
    type: "static",
    position: new Vec2(0.0, -10.0),
    angle: Math.PI * 0.1
});

platform.createFixture({
    shape: new Edge(new Vec2(-50, 0), new Vec2(+50, 0)),
})
```

The shape did not rendered, I don't know what I'm doing wrong.

**Comment by shakiba** [comment]
Hi, thanks for reporting; I'm working on this.

**Comment by oodzchen** [comment]
@shakiba It's normal now.
