### ISSUE TITLE
Save/Load everything

### ISSUE THREAD

**Issue by chavlji** [piqnt/planck.js#47]
Hi,
First thanks for this tremendous work! Awsome. I've tried Matter js, but I like physics in this one far better.

Anyway, I don't know if this is the place to ask (please point me somewere if it isn't), but is it possible to pause simulation, and save everything (bodies, forces, broadband, collision pairs,...). I would then continue simulation but in anytime I could "roll-back" everything to exact state as it was in moment of saving?

Thank you very much in advance!

**Comment by shakiba** [comment]
Currently there is nothing in the library for that, so probably closest thing to do is storing important data such positions, velocities, etc. and use them to recreated the world.

**Comment by shakiba** [comment]
Very likely will implement this in v2. There is a duplicate issues however (#36), so I close this one.
