### ISSUE TITLE
World steps in different monitors (with different frequency) ends with big differences in simulations.

### ISSUE THREAD

**Issue by lilezek** [piqnt/planck.js#74]
I'm using latest release of planck.js

With this code: 

```js
let latestTimestamp = 0;

function tick(timestamp) {
    latestTimestamp = latestTimestamp || timestamp;
    const delta = (timestamp - latestTimestamp);
    latestTimestamp = timestamp;

    world.step(1/120, delta/1000);

    window.requestAnimationFrame(tick);
}

window.requestAnimationFrame(tick);
```

Where world is a planck.World instance. I followed the information I found at https://github.com/shakiba/planck.js/issues/11

I have two monitors, one running at 60hz and another one running at 244hz. I'd like to achieve smooth simulations no matter the frequency the monitor is running. However, I can't achieve it using this library. Appart from the example above, I tried:

```js
world.step(1/120);
world.step(delta/1000);
world.step(delta);
```

None of these work, and the differences are consistent using chrome or firefox.

Any idea?

**Comment by lilezek** [comment]
I tested the demos with the two different frequencies and I found differences aswel. For instance, the asteroid demo runs different: 

![different frequencies](https://user-images.githubusercontent.com/2767229/50056767-73564580-0161-11e9-9f70-227e066096ed.gif)

First part is running at 60hz, and second part is running at 244hz.

**Comment by shakiba** [comment]
First param to `step` is step time or `1 / frequency` which is expected to be fixed, second param which is now deprecated was actual elapsed time and was used to buffer time and normalize `step` calls.

Can you please test again with just `step(1/60)` and let me know the result? Also running at different frequencies can change how user input is applied, so I recommend using an example without user input to test.

To achieve same result as second param you can use something like this:

```js
let elapsedTime = 0;
let latestTimestamp = 0;

function tick(timestamp) {
    latestTimestamp = latestTimestamp || timestamp;
    const delta = (timestamp - latestTimestamp);
    latestTimestamp = timestamp;

    elapsedTime += delta;
    while (elapsedTime > 1000 / 60) {
        world.step(1 / 60);
        elapsedTime -= 1000 / 60;
    }

    window.requestAnimationFrame(tick);
}

window.requestAnimationFrame(tick);
```

**Comment by lilezek** [comment]
I'm letting a box fall over free space with no input at 1/120 or 1/60 and both results are always different. In the monitor running with higher frequency the object reaches the floor earlier. I didn't try the sample code, just setting the TimeStep to be fixed. 

Maybe I'm wrong, but I remember using Box2d back in the days with a dynamic TimeStep being the time elapsed between frames, and it worked, even with games running at 500fps. So why is the TimeStep fixed here? 

This is something that happens aswel with the demos of MatterJS. Higher frequencies end up with simulations being faster.

**Comment by shakiba** [comment]
Generally Box2D/Planck is based on constant discrete steps, not continues simulation (so the name Planck as in Planck's constant). For example you can't do step(an hour), you need to run step(1 / 60) for 60x60x60 times.
If device lags, you can jump some frames, if it is slower you need to use a lower frequency.

**Comment by lilezek** [comment]
Thank you Shakiba for the answers, although I'm still confused. 

I understand why there is a maximum to the simulation, and stepping for an hour can be problematic. However, I don't understand why there is a minimum for the simulation. 

I think I understand what is a discrete step, however, I don't see why the discrete step must be also fixed along all the simulation. Also, if it is fixed along all the simulation, why the API lets you pass the amount of time every time you call the step? What's the difference between calling it with 1/60 and 1/120?

Also, I don't understand the relationship between the Planck's constant and the library being only for discrete simulation.
