### ISSUE TITLE
Limit world.step function to just a list of bodies.

### ISSUE THREAD

**Issue by prolightHub** [piqnt/planck.js#87]
I'd like to be able to use world.step to only update/step certain entities/bodies. By like passing in a 4th parameter or something as an array that tells world.step what to only update.

**Comment by shakiba** [comment]
Sorry, I missed this. Have you tries `body.setActive(false)` for bodies that you want to exclude from simulation? Please see doc [here](https://github.com/shakiba/planck.js/blob/master/lib/Body.js#L400).

**Comment by prolightHub** [comment]
Does it still loop through it?

**Comment by shakiba** [comment]
What do you mean by "loop through it"?
